project-path: "D:\\Document\\MyCodes\\Worker\\Codes"
config-path: "D:\\Document\\MyCodes\\Worker\\Config"
private-key-path: "C:\\Users\\Admin\\.ssh\\id_rsa"

filter:
  enable: true
  branch: test-1.1-dxj
  pull-branch: test-1.1
  dev-branch: dev-1.1-dxj
  dev-pull-branch: dev-1.1
  project-name:
    - service-housekeeping
    - service-user

branch: dev-1.1
pull-branchs:
  - test-1.1
  - test-1.2
project-name:
  - api-gateway
  - framework-core
  - rocketmq-entity
  - service-housekeeping
  - service-im
  - service-settlement
  - service-user