branch: test-1.1
private-key-path: "C:\\Users\\Admin\\.ssh\\id_rsa"
config-path: "D:\\Document\\MyCodes\\Worker\\Config"
project-path: "D:\\Document\\MyCodes\\Worker\\Codes"
project-name:
#  - api-gateway
#  - service-housekeeping
#  - service-im
#  - service-settlement
  - service-user