DROP TABLE IF EXISTS `event_data`;
CREATE TABLE `event_data`
(
    `id`                  BIGINT,
    `event` INT,
    `event_name`          STRING,
    `union_id`            BIGINT,
    `create_time`         BIGINT,
    `time_free`           INT,
    `identity_imei`       STRING,
    `identity_oaid`       STRING,
    `login_id`            BIGINT,
    `wx_open_id`          STRING,
    `wx_union_id`         STRING,
    `identity_android_id` STRING,
    `identity_mac`        STRING,
    `identity_idfa`       STRING,
    `identity_idfv`       STRING,
    `identity_mobile`     BIGINT,
    `identity_ua`         STRING,
    `app_version`         STRING,
    `is_wifi`             INT,
    `ip`    STRING,
    `manufacturer`        STRING,
    `model`               STRING,
    `os`                  STRING,
    `os_version`          STRING,
    `screen_width`        INT,
    `screen_height`       INT,
    `traffic_type`        INT,
    `promotion_channel`   INT,
    `promotion_method`    INT,
    `app_type`            INT,
    `ad_id`               INT,
    `promotion_media`     INT,
    `platform_kind`       INT
);
DROP TABLE IF EXISTS `device_user_info`;
CREATE TABLE `device_user_info`
(
    `id`                  BIGINT,
    `login_id`            STRING,
    `event_data_id`       BIGINT,
    `identity_mobile`     BIGINT,
    `wx_open_id`          STRING,
    `wx_union_id`         STRING,
    `identity_imei`       STRING,
    `identity_oaid`       STRING,
    `identity_android_id` STRING,
    `identity_mac`        STRING,
    `identity_idfa`       STRING,
    `identity_idfv`       STRING,
    `identity_ua`         STRING,
    `app_version`         STRING,
    `ip`                  STRING,
    `manufacturer`        STRING,
    `model`               STRING,
    `os`                  STRING,
    `os_version`          STRING,
    `platform_kind`       STRING
)
