DROP TABLE IF EXISTS `ods_event_data`;
CREATE TABLE `ods_event_data`
(
    `id`                  BIGINT NOT NULL DEFAULT 0,
    `event`               INT    NOT NULL DEFAULT 0,
    `event_name`          STRING NOT NULL DEFAULT '',
    `union_id`            BIGINT NOT NULL DEFAULT 0,
    `create_time`         BIGINT NOT NULL DEFAULT 0,
    `time_free`           INT    NOT NULL DEFAULT 0,
    `identity_imei`       STRING NOT NULL DEFAULT '',
    `identity_oaid`       STRING NOT NULL DEFAULT '',
    `login_id`            BIGINT NOT NULL DEFAULT 0,
    `wx_open_id`          STRING NOT NULL DEFAULT '',
    `wx_union_id`         STRING NOT NULL DEFAULT '',
    `identity_android_id` STRING NOT NULL DEFAULT '',
    `identity_mac`        STRING NOT NULL DEFAULT '',
    `identity_idfa`       STRING NOT NULL DEFAULT '',
    `identity_idfv`       STRING NOT NULL DEFAULT '',
    `identity_mobile`     BIGINT NOT NULL DEFAULT 0,
    `identity_ua`         STRING NOT NULL DEFAULT '',
    `app_version`         STRING NOT NULL DEFAULT '',
    `is_wifi`             INT    NOT NULL DEFAULT 0,
    `ip`                  STRING NOT NULL DEFAULT '',
    `manufacturer`        STRING NOT NULL DEFAULT '',
    `model`               STRING NOT NULL DEFAULT '',
    `os`                  STRING NOT NULL DEFAULT '',
    `os_version`          STRING NOT NULL DEFAULT '',
    `screen_width`        INT    NOT NULL DEFAULT 0,
    `screen_height`       INT    NOT NULL DEFAULT 0,
    `traffic_type`        INT    NOT NULL DEFAULT 0,
    `promotion_channel`   INT    NOT NULL DEFAULT 0,
    `promotion_method`    INT    NOT NULL DEFAULT 0,
    `app_type`            INT    NOT NULL DEFAULT 0,
    `ad_id`               STRING NOT NULL DEFAULT '',
    `promotion_media`     INT    NOT NULL DEFAULT 0,
    `promotion_id`        STRING NOT NULL DEFAULT '',
    `device_id`           STRING NOT NULL DEFAULT '',
    `platform_kind`       INT    NOT NULL DEFAULT 0
) tblproperties("transactional"="true");
DROP TABLE IF EXISTS `ods_device_user_info`;
CREATE TABLE `ods_device_user_info`
(
    `id`                  BIGINT NOT NULL DEFAULT 0,
    `login_id`            STRING NOT NULL DEFAULT '',
    `event_data_id`       BIGINT NOT NULL DEFAULT 0,
    `identity_mobile`     BIGINT NOT NULL DEFAULT 0,
    `wx_open_id`          STRING NOT NULL DEFAULT '',
    `wx_union_id`         STRING NOT NULL DEFAULT '',
    `identity_imei`       STRING NOT NULL DEFAULT '',
    `identity_oaid`       STRING NOT NULL DEFAULT '',
    `identity_android_id` STRING NOT NULL DEFAULT '',
    `identity_mac`        STRING NOT NULL DEFAULT '',
    `identity_idfa`       STRING NOT NULL DEFAULT '',
    `identity_idfv`       STRING NOT NULL DEFAULT '',
    `identity_ua`         STRING NOT NULL DEFAULT '',
    `app_version`         STRING NOT NULL DEFAULT '',
    `ip`                  STRING NOT NULL DEFAULT '',
    `manufacturer`        STRING NOT NULL DEFAULT '',
    `model`               STRING NOT NULL DEFAULT '',
    `os`                  STRING NOT NULL DEFAULT '',
    `device_id`           STRING NOT NULL DEFAULT '',
    `os_version`          STRING NOT NULL DEFAULT '',
    `platform_kind`       INT    NOT NULL DEFAULT 0
) tblproperties("transactional"="true")
